/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: bigint;
    status: TaskStatus;
    title: string;
    createdAt: bigint;
    dueDate?: bigint;
    description: string;
    priority: Priority;
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum TaskStatus {
    done = "done",
    todo = "todo",
    inProgress = "inProgress"
}
export enum Variant_long_short {
    long_ = "long",
    short_ = "short"
}
export interface backendInterface {
    completeSession(sessionId: bigint, breakType: Variant_long_short | null): Promise<void>;
    createTask(title: string, description: string, priority: Priority, dueDate: bigint | null): Promise<bigint>;
    deleteTask(id: bigint): Promise<void>;
    getSessionCount(): Promise<bigint>;
    getTaskById(id: bigint): Promise<Task>;
    getTasksByCreatedAt(): Promise<Array<Task>>;
    getTasksByPriority(): Promise<Array<Task>>;
    startSession(userId: string, duration: bigint): Promise<bigint>;
    updateTask(id: bigint, title: string, description: string, priority: Priority, dueDate: bigint | null): Promise<void>;
    updateTaskStatus(id: bigint, status: TaskStatus): Promise<void>;
}
import type { Priority as _Priority, Task as _Task, TaskStatus as _TaskStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeSession(arg0: bigint, arg1: Variant_long_short | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeSession(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeSession(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: Priority, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getSessionCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionCount();
            return result;
        }
    }
    async getTaskById(arg0: bigint): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskById(arg0);
                return from_candid_Task_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskById(arg0);
            return from_candid_Task_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByCreatedAt(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByCreatedAt();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByCreatedAt();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByPriority(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByPriority();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByPriority();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async startSession(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: Priority, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Priority_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    title: string;
    createdAt: bigint;
    dueDate: [] | [bigint];
    description: string;
    priority: _Priority;
}): {
    id: bigint;
    status: TaskStatus;
    title: string;
    createdAt: bigint;
    dueDate?: bigint;
    description: string;
    priority: Priority;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n8(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        priority: from_candid_Priority_n11(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    done: null;
} | {
    todo: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "done" in value ? TaskStatus.done : "todo" in value ? TaskStatus.todo : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Priority_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_long_short | null): [] | [{
        long: null;
    } | {
        short: null;
    }] {
    return value === null ? candid_none() : candid_some(to_candid_variant_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    done: null;
} | {
    todo: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.done ? {
        done: null
    } : value == TaskStatus.todo ? {
        todo: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_long_short): {
    long: null;
} | {
    short: null;
} {
    return value == Variant_long_short.long ? {
        long_: null
    } : value == Variant_long_short.short ? {
        short_: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
