/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : [] | [bigint],
  'description' : string,
  'priority' : Priority,
}
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface _SERVICE {
  'completeSession' : ActorMethod<
    [bigint, [] | [{ 'long' : null } | { 'short' : null }]],
    undefined
  >,
  'createTask' : ActorMethod<[string, string, Priority, [] | [bigint]], bigint>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getSessionCount' : ActorMethod<[], bigint>,
  'getTaskById' : ActorMethod<[bigint], Task>,
  'getTasksByCreatedAt' : ActorMethod<[], Array<Task>>,
  'getTasksByPriority' : ActorMethod<[], Array<Task>>,
  'startSession' : ActorMethod<[string, bigint], bigint>,
  'updateTask' : ActorMethod<
    [bigint, string, string, Priority, [] | [bigint]],
    undefined
  >,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];