/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  'completeSession' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null })),
      ],
      [],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, Priority, IDL.Opt(IDL.Int)],
      [IDL.Nat],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTaskById' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTasksByCreatedAt' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByPriority' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'startSession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Priority, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'priority' : Priority,
  });
  
  return IDL.Service({
    'completeSession' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null })),
        ],
        [],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, Priority, IDL.Opt(IDL.Int)],
        [IDL.Nat],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTaskById' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTasksByCreatedAt' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByPriority' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'startSession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Priority, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };